const WHIFF_OLF={
"01":{family:"WOODY · SPICY",texture:"Cool · dry · skin-close",temperature:"Cool / neutral",projection:"Intimate to moderate",longevity:"Approx. 6–8 hours",season:"Autumn · winter · evenings",top:"Saffron",heart:"Cold woods",base:"Skin musk",flavour:"Dry saffron, cool polished woods and a soft musky skin finish. Think clean paper, mineral air and warm skin rather than sweetness."},
"02":{family:"FLORAL · AMBER",texture:"Soft · warm · tender",temperature:"Warm",projection:"Intimate",longevity:"Approx. 6–8 hours",season:"Evenings · cooler weather",top:"Rose",heart:"Amber",base:"Soft woods",flavour:"Fresh rose petals warmed by amber and softened by quiet woods. Romantic without becoming sugary, with a close conversational trail."},
"03":{family:"CITRUS · AMBER · WOODY",texture:"Luminous · golden · dense",temperature:"Warm",projection:"Moderate",longevity:"Approx. 7–9 hours",season:"Autumn · winter · night",top:"Spiced citrus",heart:"Amber",base:"Warm woods",flavour:"Sparkling spiced citrus opens the door, then melts into golden amber and dark warm woods. Rich, magnetic and slightly dangerous."},
"04":{family:"SPICY · WOODY · MUSK",texture:"Dry · shadowed · smooth",temperature:"Cool / neutral",projection:"Moderate",longevity:"Approx. 7–9 hours",season:"Rain · winter · night",top:"Saffron",heart:"Dark woods",base:"Musk",flavour:"A dry saffron flash followed by shadowed woods and a restrained musky skin finish. Mysterious, polished and deliberately incomplete."},
"05":{family:"GREEN · SPICY · WOODY",texture:"Fresh · restless · grounded",temperature:"Fresh / neutral",projection:"Moderate",longevity:"Approx. 6–8 hours",season:"Spring · summer · daytime",top:"Green leaves",heart:"Spice",base:"Earthy woods",flavour:"Crushed green leaves, warm spice and earthy woods. Fresh enough to move, grounded enough to stay. Energetic without smelling juvenile."},
"06":{family:"MUSK · SKIN · WOODY",texture:"Clean · soft · intimate",temperature:"Warm / neutral",projection:"Intimate",longevity:"Approx. 5–7 hours",season:"All year · daytime · close evenings",top:"Clean musk",heart:"Skin accord",base:"Soft woods",flavour:"The smell of clean skin, fresh fabric and warm proximity. Soft musk sits close while smooth woods create a barely-there foundation."},
"07":{family:"CITRUS · SMOKY · WOODY",texture:"Bright · smoky · dry",temperature:"Cool / neutral",projection:"Moderate",longevity:"Approx. 6–8 hours",season:"Rain · autumn · evening",top:"Orange peel",heart:"Smoke",base:"Dry woods",flavour:"Bitter orange peel catches the light, smoke moves through it, and dry woods remain after the brightness disappears. Beautifully melancholic."},
"08":{family:"SPICY · WOODY · AMBER MUSK",texture:"Familiar · warm · textured",temperature:"Warm",projection:"Moderate",longevity:"Approx. 7–9 hours",season:"Autumn · winter · quiet days",top:"Warm spice",heart:"Woods",base:"Amber musk",flavour:"Warm spice, old wood and ambered skin. It suggests books, wooden drawers, familiar rooms and the strange comfort of returning somewhere you remember."},
"09":{family:"FLORAL · AMBER · MUSK",texture:"Rich · luminous · intimate",temperature:"Warm",projection:"Moderate",longevity:"Approx. 7–9 hours",season:"Evenings · celebrations · dates",top:"Rose",heart:"Warm amber",base:"Musk",flavour:"A rich rose declaration softened by warm amber and brought back to skin by musk. Romantic, full-bodied and confident without becoming loud."}
};
(function(){
 const root=document.querySelector('[data-stage-page]'); if(!root)return;
 const id=root.dataset.stage, d=WHIFF_OLF[id]; if(!d)return;
 const architecture=document.querySelector('.architecture');
 if(!architecture || document.querySelector('.olfactiveDetails'))return;
 const el=document.createElement('section'); el.className='olfactiveDetails'; el.innerHTML=`<div class="olfactiveDetailsHead"><span class="mono">THE PERFUME / ${id}</span><h2>MORE THAN<br>A NOTE LIST.</h2><p>Notes tell you what is inside the story. These details tell you how the fragrance behaves, feels and changes on skin. These are olfactive descriptions, not the final INCI ingredient declaration.</p></div><div class="olfactiveDetailsGrid"><div class="flavourCard flavourMain"><span class="mono">WHAT IT SMELLS LIKE</span><h3>${d.flavour}</h3></div><div class="flavourCard"><span class="mono">OLFACTIVE FAMILY</span><strong>${d.family}</strong></div><div class="flavourCard"><span class="mono">TEXTURE</span><strong>${d.texture}</strong></div><div class="flavourCard"><span class="mono">TEMPERATURE</span><strong>${d.temperature}</strong></div><div class="flavourCard"><span class="mono">PROJECTION</span><strong>${d.projection}</strong></div><div class="flavourCard"><span class="mono">LONGEVITY</span><strong>${d.longevity}</strong></div><div class="flavourCard"><span class="mono">BEST SEASON</span><strong>${d.season}</strong></div></div><div class="notePyramid"><span class="mono">THE PYRAMID / HOW IT UNFOLDS</span><div><article><small>00:00</small><b>TOP</b><strong>${d.top}</strong><p>The first impression. Brightest, quickest and most volatile.</p></article><article><small>00:30–02:00</small><b>HEART</b><strong>${d.heart}</strong><p>The emotional centre. Where the fragrance finds its identity.</p></article><article><small>02:00+</small><b>BASE</b><strong>${d.base}</strong><p>The drydown. What remains on skin and in memory.</p></article></div></div><div class="ingredientsNote"><span class="mono">INGREDIENTS / IMPORTANT</span><p>Fragrance notes are an olfactive description. They are not a complete list of raw materials or chemical ingredients. The final INCI declaration will be published separately with the finished compliant formula.</p></div>`;
 architecture.insertAdjacentElement('afterend',el);
})();