const WHIFF={
  currency:new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}),
  mrp:399,
  sale:299,
  firstOrder:50,
  collectionPrice:2499,
  whatsappNumber:'',
  stages:[
    ['01','AJAAB','The unfamiliar','#255bd3','#f3ecdf',['Saffron','Cold woods']],
    ['02','UNS','The longing','#b63b39','#f3ecdf',['Rose','Amber']],
    ['03','KHUMAAR','The intoxication','#63202d','#f3ecdf',['Amber','Warm woods']],
    ['04','ASRAAR','The mystery','#17191d','#67a0ff',['Saffron','Dark woods']],
    ['05','TALAB','The desire','#164f43','#ef674a',['Green','Spice']],
    ['06','QURBAT','The closeness','#82c3df','#b72d30',['Musk','Soft woods']],
    ['07','FIRAQ','The separation','#17191d','#f28a16',['Smoke','Orange peel']],
    ['08','YAAD','The memory','#b7861f','#74263d',['Woods','Spice']],
    ['09','ISHQ','The surrender','#b63b39','#f3ecdf',['Rose','Musk']]
  ]
};
function cart(){try{return JSON.parse(localStorage.getItem('whiff-cart')||'[]')}catch{return[]}}
function saveCart(c){localStorage.setItem('whiff-cart',JSON.stringify(c));renderCartCount()}
function addToCart(id,qty=1){const c=cart();const found=c.find(x=>x.id===id);if(found)found.qty+=qty;else c.push({id,qty});saveCart(c);toast('Added to your stages');return c}
function removeFromCart(id){saveCart(cart().filter(x=>x.id!==id));renderCart()}
function setQty(id,qty){const c=cart();const item=c.find(x=>x.id===id);if(!item)return;if(qty<1)return removeFromCart(id);item.qty=qty;saveCart(c);renderCart()}
function cartItems(){return cart().map(x=>{const s=WHIFF.stages.find(y=>y[0]===x.id);return s?{...x,s}:null}).filter(Boolean)}
function totals(first=false){const items=cartItems();const count=items.reduce((a,x)=>a+x.qty,0);const mrp=count*WHIFF.mrp;let subtotal=count===9?WHIFF.collectionPrice:count*WHIFF.sale;let discount=count===9?count*WHIFF.mrp-WHIFF.collectionPrice:count*(WHIFF.mrp-WHIFF.sale);let firstDiscount=first?Math.min(WHIFF.firstOrder,subtotal):0;return{count,mrp,subtotal,discount,firstDiscount,total:Math.max(0,subtotal-firstDiscount)}}
function renderCartCount(){document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=cart().reduce((a,x)=>a+x.qty,0))}
function money(n){return WHIFF.currency.format(n).replace('₹','₹')}
function toast(t){let e=document.querySelector('.toast');if(!e){e=document.createElement('div');e.className='toast';document.body.appendChild(e)}e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function renderCart(){const root=document.querySelector('[data-cart]');if(!root)return;const items=cartItems();if(!items.length){root.innerHTML='<div class="emptyCart"><span class="mono">YOUR CART / 00</span><h2>NOTHING<br>HERE YET.</h2><a class="btn" href="/\#collection">Explore STAGES</a></div>';return}const t=totals(false);root.innerHTML='<div class="cartList">'+items.map(x=>`<article class="cartItem"><div class="cartSwatch" style="background:${x.s[3]};color:${x.s[4]}"><span>${x.s[0]}</span><b>${x.s[1]}</b></div><div class="cartInfo"><span class="mono">STAGES / ${x.s[0]}</span><h3>${x.s[1]}</h3><p>30 ml · Eau de parfum</p><div class="qty"><button onclick="setQty('${x.id}',${x.qty-1})">−</button><b>${x.qty}</b><button onclick="setQty('${x.id}',${x.qty+1})">+</button><button class="remove" onclick="removeFromCart('${x.id}')">Remove</button></div></div><strong>${money(x.qty*WHIFF.sale)}</strong></article>`).join('')+'</div><div class="cartSummary"><span class="mono">ORDER SUMMARY</span><div><span>MRP</span><b>${money(t.mrp)}</b></div><div><span>STAGES price</span><b>${money(t.subtotal)}</b></div><div class="saving"><span>You save</span><b>−${money(t.discount)}</b></div><div class="total"><span>Total</span><b>${money(t.subtotal)}</b></div><a class="btn fill" href="/checkout.html">Continue to order</a><button class="whatsappBtn" onclick="whatsappOrder(false)">Order on WhatsApp</button></div>'}
function whatsappText(first=false,customer={}){const t=totals(first);const items=cartItems();let lines=['WHIFF / HOUSE OF WHIFF','COLLECTION 01 · STAGES','',...items.map(x=>`${x.s[0]} ${x.s[1]} × ${x.qty} = ${money(x.qty*WHIFF.sale)}`),'',`MRP: ${money(t.mrp)}`,`STAGES price: ${money(t.subtotal)}`];if(t.firstDiscount)lines.push(`First order discount: −${money(t.firstDiscount)}`);lines.push(`TOTAL: ${money(t.total)}`);if(customer.name)lines.push('',`Name: ${customer.name}`,`Phone: ${customer.phone}`,`Address: ${customer.address}`,customer.note?`Note: ${customer.note}`:'');return encodeURIComponent(lines.join('\n'))}
function whatsappOrder(first=false,customer={}){const text=whatsappText(first,customer);const url=WHIFF.whatsappNumber?`https://wa.me/${WHIFF.whatsappNumber}?text=${text}`:`https://wa.me/?text=${text}`;window.open(url,'_blank','noopener')}
function renderCheckout(){const root=document.querySelector('[data-checkout]');if(!root)return;const items=cartItems();const t=totals(false);root.innerHTML=`<div class="checkoutGrid"><form id="orderForm" class="orderForm"><span class="mono">01 / YOUR DETAILS</span><h2>MAKE IT<br>YOURS.</h2><label>Name<input name="name" required placeholder="Your name"></label><label>Phone<input name="phone" required inputmode="tel" placeholder="10 digit number"></label><label>Address<textarea name="address" required placeholder="Delivery address"></textarea></label><label>Note <span class="optional">optional</span><textarea name="note" placeholder="Anything we should know?"></textarea></label><label class="check"><input type="checkbox" name="first"> <span>It's my first WHIFF order. Apply flat ₹50 off.</span></label><button class="btn fill" type="submit">Place order</button><button class="whatsappBtn" type="button" id="waCheckout">Send order to WhatsApp</button><p class="formNote">No payment is taken on this page. Your order is sent to WHIFF for confirmation and payment instructions.</p></form><aside class="checkoutSide"><span class="mono">02 / YOUR STAGES</span><div class="miniCart">${items.map(x=>`<div><span>${x.s[0]} · ${x.s[1]} × ${x.qty}</span><b>${money(x.qty*WHIFF.sale)}</b></div>`).join('')}</div><div class="priceBox"><div><span>MRP</span><b>${money(t.mrp)}</b></div><div><span>Collection pricing</span><b>−${money(t.discount)}</b></div><div class="bigTotal"><span>Total before first order offer</span><b>${money(t.subtotal)}</b></div><p>First order? Get another ₹50 off at checkout.</p></div></aside></div>`;document.getElementById('orderForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const first=!!d.first;const t=totals(first);localStorage.setItem('whiff-last-order',JSON.stringify({customer:d,total:t.total,items:cartItems()}));whatsappOrder(first,d);window.location.href='/thank-you.html'});document.getElementById('waCheckout').addEventListener('click',()=>{const f=document.getElementById('orderForm');if(!f.reportValidity())return;const d=Object.fromEntries(new FormData(f));whatsappOrder(!!d.first,d)})}
window.addToCart=addToCart;window.removeFromCart=removeFromCart;window.setQty=setQty;window.whatsappOrder=whatsappOrder;document.addEventListener('DOMContentLoaded',()=>{renderCartCount();renderCart();renderCheckout()});
